-- PRIMERO ES NECESARIO REVOCAR TODOS LOS PRIVILEGIOS DE LOS USUARIOS AL CREAR UNA BASE DE DATOS
-- REVOKE ALL PRIVILEGES ON DATABASE "database_name" from "username"; 

-- NOS CONECTAMOS CON EL USUARIO SUPERUSER DE POSTGRES PARA CREAR LOS SIGUIENTES 2 USUARIOS

create role JEFE with nocreatedb nocreaterole nologin noinherit password 'JEFE';	
create role PIPEMAX with nocreatedb nocreaterole nologin noinherit password 'PIPEMAX';
create role ADMINS with nocreatedb nocreaterole nologin noinherit password 'ADMINS';

-- SE OTORGAN TODOS LOS PRIVILEGIOS AL JEFE
GRANT ALL PRIVILEGES ON SCHEMA PUBLIC TO JEFE;
GRANT INSERT,UPDATE,DELETE,SELECT ON ALL TABLES IN SCHEMA public TO admins;

-- SE OTORGA EL PRIVILEGIO DE CONEXIÓN Y USO DE LA BASE DE DATOS "arriendo" A PIPEMAX;
GRANT CONNECT ON DATABASE arriendo TO pipemax;
GRANT USAGE ON SCHEMA public to pipemax;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO pipemax;
GRANT CONNECT ON DATABASE arriendo TO admins;
GRANT USAGE ON SCHEMA public TO admins;

/*SE REVOCAN TODOS LOS PERMISOS DE CRUD PARA PIPEMAX 
  POSTERIORMENTE SE ASIGNARÁN DE ACUERDO A LO QUE EL USUARIO "EXTERIOR" PUEDE HACER
*/
REVOKE INSERT ON ALL TABLES IN SCHEMA PUBLIC FROM PIPEMAX;
REVOKE DELETE ON ALL TABLES IN SCHEMA PUBLIC FROM PIPEMAX;
REVOKE UPDATE ON ALL TABLES IN SCHEMA PUBLIC FROM PIPEMAX;

-- PERMISOS PARA ADMINS
GRANT EXECUTE ON FUNCTION INICIO_SESION_ADMIN TO ADMINS;
GRANT EXECUTE ON FUNCTION VALIDACION(int) TO ADMINS;
GRANT EXECUTE ON FUNCTION CHECKADMIN TO ADMINS;
GRANT EXECUTE ON FUNCTION VALIDAR_LOGIN_ADMIN TO ADMINS;
grant execute on function verificar_descuentos to pipemax;
GRANT USAGE ON SEQUENCE SUCURSAL_AI TO ADMINS;


-- SE OTORGAN LOS PERMISOS DE SELECT A PIPEMAX SOBRE LAS TABLAS
GRANT SELECT ON public.usuario TO pipemax;
GRANT UPDATE ON public.usuario TO pipemax;
GRANT SELECT ON public.arriendo TO pipemax;
GRANT SELECT ON public.detalle TO pipemax;
GRANT SELECT ON public.herramienta TO pipemax;
GRANT SELECT ON public.categoria TO pipemax;
GRANT SELECT ON public.sucursal TO pipemax;
GRANT SELECT ON public.carrito TO pipemax;
GRANT SELECT ON public.sucursal_herramienta TO pipemax;
GRANT INSERT ON public.usuario TO pipemax;
GRANT INSERT ON public.carrito TO pipemax;
GRANT UPDATE ON public.carrito TO pipemax;
GRANT DELETE ON public.carrito TO pipemax;
GRANT USAGE ON SEQUENCE ARRIENDO_AI TO pipemax;
GRANT INSERT ON public.arriendo TO pipemax;
GRANT UPDATE ON public.arriendo TO pipemax;
GRANT INSERT ON public.detalle TO pipemax;
GRANT SELECT ON public.region TO pipemax;
GRANT SELECT ON public.provincia to pipemax;
GRANT SELECT ON public.comuna to pipemax;
GRANT SELECT ON public.empresa to pipemax;
GRANT UPDATE ON public.sucursal_herramienta to pipemax;



    

    