DROP TABLE DETALLE;
DROP SEQUENCE ARRIENDO_AI;
DROP SEQUENCE CATEGORIA_AI;
DROP SEQUENCE SUCURSAL_AI;
DROP TABLE SUCURSAL_HERRAMIENTA;
DROP TABLE ARRIENDO;
DROP TABLE USUARIO;
DROP TABLE SUCURSAL;
DROP TABLE HERRAMIENTA;
DROP TABLE CATEGORIA;
DROP TABLE CARRITO;


CREATE TABLE USUARIO(
    RUT INT,
    NOMBRES VARCHAR(40),
    APELLIDOS VARCHAR(40),
    CORREO VARCHAR(50),
    ROL VARCHAR(20),
    PASS VARCHAR(100),
    ESTADO INT,
    DIRECCION VARCHAR(50),
    CELULAR INT
);

CREATE SEQUENCE ARRIENDO_AI
    MINVALUE 1
    START WITH 1
    INCREMENT BY 1
    CACHE 30;    
    
CREATE SEQUENCE CATEGORIA_AI
    MINVALUE 1
    START WITH 1
    INCREMENT BY 1
    CACHE 30;
    
CREATE SEQUENCE SUCURSAL_AI
    MINVALUE 1
    START WITH 1
    INCREMENT BY 1
    CACHE 30;

CREATE SEQUENCE EMPRESA_AI
    MINVALUE 1
    START WITH 1
    INCREMENT BY 1
    CACHE 30;

CREATE TABLE ARRIENDO(
    COD_ARRIENDO INT,
    FECHA_INICIO DATE,
    FECHA_FINAL DATE,
    TOTAL INT,
    RUT_U INT,
    COD_S INT,
    ESTADO VARCHAR(20),
    FECHA_ARRIENDO DATE
);
--ALTER TABLE ARRIENDO ADD FECHA_ARRIENDO DATE;

CREATE TABLE DETALLE(
    COD_H INT,
    CANTIDAD INT,
    TOTAL_DETALLE INT,
    ID_A INT
);

CREATE TABLE HERRAMIENTA(
    COD_HERRAMIENTA INT,
    NOMBRE VARCHAR(100),
    DESCRIPCION VARCHAR(200),
    URL_FOTO VARCHAR(100),
    COD_CATEGORIA INT
);

CREATE TABLE SUCURSAL_HERRAMIENTA(
    COD_HERRAMIENTA INT,
    COD_SUCURSAL INT,
    STOCK INT,
    PRECIO INT
);
--ALTER TABLE SUCURSAL_HERRAMIENTA ADD PRECIO INT;
--ALTER TABLE HERRAMIENTA MODIFY NOMBRE VARCHAR(50);

CREATE TABLE CATEGORIA(
    COD_CATEGORIA INT,
    NOMBRE VARCHAR(30)
);

CREATE TABLE SUCURSAL(
    COD_SUCURSAL INT,
    NOMBRE VARCHAR(30),
    DIRECCION VARCHAR(100),
    TELEFONO INT,
    URL_FOTO VARCHAR(100),
    COD_EMPRESA INT,
    REGION INT,
    CIUDAD VARCHAR(50)
);

--ALTER TABLE SUCURSAL ADD COD_EMPRESA INT;

CREATE TABLE CARRITO(
    COD_HERRAMIENTA INT,
    COD_SUCURSAL INT,
    RUT INT,
    CANTIDAD INT,
    TOTAL INT
);

CREATE TABLE EMPRESA(
    COD_EMPRESA INT,
    NOMBRE VARCHAR(100)
);

--ALTER TABLE CARRITO ADD COD_SUCURSAL INT;

--ALTER TABLE PRIMARY KEY
/*
    DROP CONSTRAINT PK_USUARIO;
    DROP CONSTRAINT PK_ARRIENDO;
    DROP CONSTRAINT PK_DETALLE;
    DROP CONSTRAINT PK_HERRAMIENTA;
    DROP CONSTRAINT PK_CATEGORIA;
    DROP CONSTRAINT PK_SUCURSAL;

*/
ALTER TABLE USUARIO ADD CONSTRAINT PK_USUARIO PRIMARY KEY(RUT);
ALTER TABLE ARRIENDO ADD CONSTRAINT PK_ARRIENDO PRIMARY KEY(COD_ARRIENDO);
ALTER TABLE DETALLE ADD CONSTRAINT PK_DETALLE PRIMARY KEY(COD_H,ID_A);
ALTER TABLE HERRAMIENTA ADD CONSTRAINT PK_HERRAMIENTA PRIMARY KEY(COD_HERRAMIENTA);
ALTER TABLE CATEGORIA ADD CONSTRAINT PK_CATEGORIA PRIMARY KEY(COD_CATEGORIA);
ALTER TABLE SUCURSAL ADD CONSTRAINT PK_SUCURSAL PRIMARY KEY(COD_SUCURSAL);
ALTER TABLE CARRITO ADD CONSTRAINT PK_CARRITO PRIMARY KEY(COD_HERRAMIENTA,RUT);
ALTER TABLE SUCURSAL_HERRAMIENTA ADD CONSTRAINT PK_SUCURSAL_HERRAMIENTA PRIMARY KEY(COD_HERRAMIENTA,COD_SUCURSAL);
ALTER TABLE EMPRESA ADD CONSTRAINT PK_EMPRESA PRIMARY KEY(COD_EMPRESA);


--ALTER TABLE FOREIGN KEY
/*
    DROP CONSTRAINT FK_USUARIO;
    DROP CONSTRAINT FK_SUCURSAL;
    DROP CONSTRAINT FK_ARRIENDO;
    DROP CONSTRAINT FK_HERRAMIENTA;
    DROP CONSTRAINT FK_CATEGORIA;
*/

ALTER TABLE ARRIENDO ADD CONSTRAINT FK_USUARIO FOREIGN KEY(RUT_U) REFERENCES USUARIO(RUT) ON DELETE CASCADE;
ALTER TABLE ARRIENDO ADD CONSTRAINT FK_SUCURSAL FOREIGN KEY(COD_S) REFERENCES SUCURSAL(COD_SUCURSAL) ON DELETE CASCADE;
ALTER TABLE DETALLE ADD CONSTRAINT FK_ARRIENDO FOREIGN KEY(ID_A) REFERENCES ARRIENDO(COD_ARRIENDO) ON DELETE CASCADE;
ALTER TABLE DETALLE ADD CONSTRAINT FK_HERRAMIENTA FOREIGN KEY(COD_H) REFERENCES HERRAMIENTA(COD_HERRAMIENTA) ON DELETE CASCADE;
ALTER TABLE HERRAMIENTA ADD CONSTRAINT FK_CATEGORIA FOREIGN KEY(COD_CATEGORIA) REFERENCES CATEGORIA(COD_CATEGORIA) ON DELETE CASCADE;
ALTER TABLE CARRITO ADD CONSTRAINT FK_CARRITO FOREIGN KEY(RUT) REFERENCES USUARIO(RUT) ON DELETE CASCADE;
ALTER TABLE CARRITO ADD CONSTRAINT FK_CARRITO1 FOREIGN KEY(COD_HERRAMIENTA) REFERENCES HERRAMIENTA(COD_HERRAMIENTA) ON DELETE CASCADE;
ALTER TABLE CARRITO ADD CONSTRAINT FK_CARRITO2 FOREIGN KEY(COD_SUCURSAL) REFERENCES SUCURSAL(COD_SUCURSAL) ON DELETE CASCADE;
ALTER TABLE SUCURSAL_HERRAMIENTA ADD CONSTRAINT FK_SUCURSAL_HERRAMIENTA FOREIGN KEY(COD_HERRAMIENTA) REFERENCES HERRAMIENTA(COD_HERRAMIENTA) ON DELETE CASCADE;
ALTER TABLE SUCURSAL_HERRAMIENTA ADD CONSTRAINT FJ_SUCURSAL_HERRAMIENTA2 FOREIGN KEY(COD_SUCURSAL) REFERENCES SUCURSAL(COD_SUCURSAL) ON DELETE CASCADE;    
ALTER TABLE SUCURSAL ADD CONSTRAINT FK_SUCURSAL FOREIGN KEY(COD_EMPRESA) REFERENCES EMPRESA(COD_EMPRESA) ON DELETE CASCADE;