CREATE OR REPLACE FUNCTION VERIFICA_HERRAMIENTA_SUCURSAL(
    CODIGO IN SUCURSAL_HERRAMIENTA.COD_HERRAMIENTA%TYPE,
    CODIGO_S IN SUCURSAL_HERRAMIENTA.COD_SUCURSAL%TYPE)
    RETURN BOOLEAN
IS
    CONTADOR NUMBER;
BEGIN
    SELECT COUNT(*) INTO CONTADOR FROM SUCURSAL_HERRAMIENTA WHERE COD_HERRAMIENTA = CODIGO AND COD_SUCURSAL = CODIGO_S;
    IF (CONTADOR>0) THEN
        RETURN TRUE;
    ELSE
        RETURN FALSE;
    END IF;
END;


CREATE OR REPLACE FUNCTION CHECKSUCURSAL(
    CODIGO IN NUMBER)
    RETURN BOOLEAN
IS
    CONTADOR NUMBER;
BEGIN 
    SELECT COUNT(*) INTO CONTADOR FROM SUCURSAL WHERE COD_SUCURSAL=CODIGO;
    IF (CONTADOR>0) THEN
        RETURN TRUE;
    ELSE
        RETURN FALSE;
    END IF;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RETURN FALSE;
        WHEN OTHERS THEN
            RETURN FALSE;
END;    


CREATE OR REPLACE FUNCTION CHECK_FECHA_FINAL(
    FINICIO IN DATE,
    FFINAL IN DATE)
    RETURN BOOLEAN
IS
BEGIN
    IF FFINAL>FINICIO THEN
        RETURN TRUE;
    ELSE
        RETURN FALSE;
    END IF;
END;

CREATE OR REPLACE FUNCTION CHECK_CANTIDAD_CARRITO(
    CODIGO IN HERRAMIENTA.COD_HERRAMIENTA%TYPE,
    CODIGO_S IN SUCURSAL_HERRAMIENTA.COD_SUCURSAL%TYPE,
    RUT_U IN CARRITO.RUT%TYPE)
    RETURN NUMBER
IS 
    CANTIDAD_CARRO NUMBER;
BEGIN
    SELECT CANTIDAD INTO CANTIDAD_CARRO FROM CARRITO 
    WHERE COD_HERRAMIENTA=CODIGO
    AND COD_SUCURSAL = CODIGO_S
    AND RUT = RUT_U;
    RETURN CANTIDAD_CARRO;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RETURN -1;
END;
    
CREATE OR REPLACE FUNCTION CHECKCARRITO(
    CODIGO IN HERRAMIENTA.COD_HERRAMIENTA%TYPE,
    CODIGO_S IN SUCURSAL_HERRAMIENTA.COD_SUCURSAL%TYPE,
    RUT_U IN CARRITO.RUT%TYPE)
    RETURN BOOLEAN
IS
    CONTADOR NUMBER;
BEGIN
    SELECT COUNT(*) INTO CONTADOR FROM CARRITO 
    WHERE COD_HERRAMIENTA=CODIGO
    AND COD_SUCURSAL = CODIGO_S
    AND RUT = RUT_U;
    IF(CONTADOR>0) THEN
        RETURN TRUE;
    ELSE
        RETURN FALSE;
    END IF;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RETURN FALSE;
        WHEN OTHERS THEN
            RETURN FALSE;
END;

CREATE OR REPLACE FUNCTION CHECKSTOCK(
    CODIGO IN SUCURSAL_HERRAMIENTA.COD_HERRAMIENTA%TYPE,
    CODIGO_S IN SUCURSAL_HERRAMIENTA.COD_SUCURSAL%TYPE,
    FECHA_I IN VARCHAR2,
    FECHA_F IN VARCHAR2)
    RETURN NUMBER
IS
    CANTIDAD NUMBER;
BEGIN    
    SELECT STOCK INTO CANTIDAD FROM
    (SELECT (SH.STOCK - SUM(D.CANTIDAD)) AS STOCK
    FROM HERRAMIENTA H JOIN CATEGORIA C 
    ON H.COD_CATEGORIA=C.COD_CATEGORIA
    JOIN SUCURSAL_HERRAMIENTA SH
    ON H.COD_HERRAMIENTA = SH.COD_HERRAMIENTA
    JOIN DETALLE D 
    ON D.COD_H=H.COD_HERRAMIENTA
    WHERE H.COD_HERRAMIENTA IN (SELECT H.COD_HERRAMIENTA FROM ARRIENDO A JOIN DETALLE D 
                                    ON A.COD_ARRIENDO=D.ID_A JOIN HERRAMIENTA H
                                    ON D.COD_H=H.COD_HERRAMIENTA
                                    WHERE A.FECHA_INICIO BETWEEN TO_DATE(FECHA_I,'DD/MM/YYYY') AND TO_DATE(FECHA_F,'DD/MM/YYYY')
                                    OR A.FECHA_FINAL BETWEEN TO_DATE(FECHA_I,'DD/MM/YYYY') AND TO_DATE(FECHA_F,'DD/MM/YYYY')
                                    AND H.COD_HERRAMIENTA = CODIGO)
    AND SH.COD_SUCURSAL = CODIGO_S
    AND SH.COD_HERRAMIENTA = CODIGO
    GROUP BY H.COD_HERRAMIENTA, H.NOMBRE, H.DESCRIPCION, H.URL_FOTO, SH.PRECIO, C.NOMBRE, SH.STOCK   
    UNION 
    SELECT SH.STOCK AS STOCK
    FROM HERRAMIENTA H JOIN CATEGORIA C 
    ON H.COD_CATEGORIA=C.COD_CATEGORIA
    JOIN SUCURSAL_HERRAMIENTA SH
    ON H.COD_HERRAMIENTA = SH.COD_HERRAMIENTA
    FULL OUTER JOIN DETALLE D 
    ON D.COD_H=H.COD_HERRAMIENTA
    WHERE H.COD_HERRAMIENTA NOT IN (SELECT H.COD_HERRAMIENTA FROM ARRIENDO A JOIN DETALLE D 
                                ON A.COD_ARRIENDO=D.ID_A JOIN HERRAMIENTA H
                                ON D.COD_H=H.COD_HERRAMIENTA
                                WHERE A.FECHA_INICIO BETWEEN TO_DATE(FECHA_I,'DD/MM/YYYY') AND TO_DATE(FECHA_F,'DD/MM/YYYY')
                                OR A.FECHA_FINAL BETWEEN TO_DATE(FECHA_I,'DD/MM/YYYY') AND TO_DATE(FECHA_F,'DD/MM/YYYY')
                                AND H.COD_HERRAMIENTA = CODIGO)
    AND SH.COD_SUCURSAL = CODIGO_S
    AND SH.COD_HERRAMIENTA = CODIGO);
    RETURN CANTIDAD;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN            
            SELECT STOCK INTO CANTIDAD FROM SUCURSAL_HERRAMIENTA WHERE COD_HERRAMIENTA=CODIGO AND COD_SUCURSAL = CODIGO_S;
            RETURN CANTIDAD;
END;
    

CREATE OR REPLACE FUNCTION CHECKCATEGORIA(
    CODIGO IN CATEGORIA.COD_CATEGORIA%TYPE)
    RETURN BOOLEAN
IS
    CONTADOR NUMBER;
BEGIN
    SELECT COUNT(*) INTO CONTADOR FROM CATEGORIA WHERE COD_CATEGORIA=CODIGO;
    IF(CONTADOR>0) THEN
        RETURN TRUE;
    ELSE 
        RETURN FALSE;
    END IF;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RETURN FALSE;
        WHEN OTHERS THEN
            RETURN FALSE;
END;

CREATE OR REPLACE FUNCTION GETPASS(
    RUT_U IN USUARIO.RUT%TYPE)
    RETURN VARCHAR2
IS  
    PASS_U VARCHAR2(100);      
BEGIN
    IF(CHECKUSER(RUT_U)=TRUE) THEN
        SELECT PASS INTO PASS_U FROM USUARIO WHERE RUT=RUT_U;
        RETURN PASS_U;
    ELSE
        RETURN 'FALSE';
    END IF;
    EXCEPTION
        WHEN INVALID_NUMBER THEN
            RETURN 'FALSE';
        WHEN NO_DATA_FOUND THEN
            RETURN 'FALSE';
        WHEN OTHERS THEN 
            RETURN 'FALSE';
END;

CREATE OR REPLACE FUNCTION CHECKHERRAMIENTA(
    CODIGO IN NUMBER)
    RETURN BOOLEAN
IS 
    CONTADOR NUMBER;
BEGIN
    SELECT COUNT(*) INTO CONTADOR FROM HERRAMIENTA WHERE COD_HERRAMIENTA=CODIGO;
    IF(CONTADOR>0) THEN
        RETURN TRUE;
    ELSE
        RETURN FALSE;
    END IF;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RETURN FALSE;
        WHEN OTHERS THEN
            RETURN FALSE;
END;

CREATE OR REPLACE FUNCTION CHECKUSER(
    RUT_U IN NUMBER)
    RETURN BOOLEAN
IS 
    CONTADOR NUMBER;
BEGIN
    SELECT COUNT(*) INTO CONTADOR FROM USUARIO WHERE RUT=RUT_U;
    IF(CONTADOR>0) THEN
        RETURN TRUE;
    ELSE
        RETURN FALSE;
    END IF;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RETURN FALSE;
        WHEN OTHERS THEN
            RETURN FALSE;
END;

CREATE OR REPLACE FUNCTION VALIDACION(
  NUMERICO IN USUARIO.RUT%TYPE)
  RETURN BOOLEAN
IS
  truerut VARCHAR2(9);
  digito number := 0;
  suma number := 0;
  digitof number :=0;
  largo number := LENGTH(NUMERICO);
BEGIN
  IF(largo=8) THEN
    TRUERUT := LPAD(NUMERICO,9,'0'); --agrega ceros al comienzo hasta alcanzar un lenght de 9
  ELSE
    TRUERUT := NUMERICO;
  END IF;
  digito := SUBSTR(TRUERUT,9,1);
  suma := SUBSTR(TRUERUT,1,1) * 3;
  suma := (suma + SUBSTR(TRUERUT,2,1) * 2);
  suma := (suma + SUBSTR(TRUERUT,3,1) * 7);
  suma := (suma + SUBSTR(TRUERUT,4,1) * 6);
  suma := (suma + SUBSTR(TRUERUT,5,1) * 5);
  suma := (suma + SUBSTR(TRUERUT,6,1) * 4);
  suma := (suma + SUBSTR(TRUERUT,7,1) * 3);
  suma := (suma + SUBSTR(TRUERUT,8,1) * 2);
  WHILE (suma > 11) LOOP 
    suma := suma - 11; 
  END LOOP; 
  digitof := (11 - suma);
  IF (digitof=10) THEN
    digitof:= 0;
  END IF;
  IF (digitof=digito) THEN
    RETURN TRUE;
    --DBMS_OUTPUT.PUT_LINE('EL RUT ES VALIDO');
  ELSE
    RETURN FALSE;
    --DBMS_OUTPUT.PUT_LINE('EL RUT ES NO VALIDO');
  END IF;
END; 

DECLARE
    RETORNO NUMBER;
BEGIN
    RETORNO := VERIFICAR_PRODUCTO_VENTA('08/08/2018','09/08/2018',1,1);
    DBMS_OUTPUT.PUT_LINE(RETORNO);
END;




CREATE OR REPLACE FUNCTION VERIFICAR_PRODUCTO_VENTA(
    FECHA_I IN ARRIENDO.FECHA_INICIO%TYPE,
    FECHA_F IN ARRIENDO.FECHA_FINAL%TYPE,
    COD_S IN SUCURSAL.COD_SUCURSAL%TYPE,
    COD_HE IN SUCURSAL_HERRAMIENTA.COD_HERRAMIENTA%TYPE)
    RETURN NUMBER
IS
    CANTIDADES NUMBER;
    VERIFICADOR NUMBER;
BEGIN
    CANTIDADES := 0;
    SELECT COUNT(*) INTO VERIFICADOR
    FROM SUCURSAL_HERRAMIENTA
    WHERE COD_HERRAMIENTA = COD_HE
    AND COD_SUCURSAL = COD_S;
    IF VERIFICADOR > 0 THEN    
        SELECT * INTO CANTIDADES FROM
        (SELECT SH.STOCK - SUM(D.CANTIDAD)
        FROM HERRAMIENTA H JOIN CATEGORIA C 
        ON H.COD_CATEGORIA=C.COD_CATEGORIA
        JOIN SUCURSAL_HERRAMIENTA SH
        ON H.COD_HERRAMIENTA = SH.COD_HERRAMIENTA
        FULL OUTER JOIN DETALLE D 
        ON D.COD_H=H.COD_HERRAMIENTA
        WHERE H.COD_HERRAMIENTA IN (SELECT H.COD_HERRAMIENTA FROM ARRIENDO A JOIN DETALLE D 
                                    ON A.COD_ARRIENDO=D.ID_A JOIN HERRAMIENTA H
                                    ON D.COD_H=H.COD_HERRAMIENTA
                                    WHERE A.FECHA_INICIO BETWEEN FECHA_I AND FECHA_F
                                    OR A.FECHA_FINAL BETWEEN FECHA_I AND FECHA_F)
        AND SH.COD_SUCURSAL = COD_S
        AND SH.COD_HERRAMIENTA = COD_HE
        GROUP BY H.COD_HERRAMIENTA, H.NOMBRE, H.DESCRIPCION, H.URL_FOTO, SH.PRECIO, C.NOMBRE, SH.STOCK
        HAVING (SH.STOCK - SUM(D.CANTIDAD)) > 0
        UNION 
        SELECT SH.STOCK
        FROM HERRAMIENTA H JOIN CATEGORIA C 
        ON H.COD_CATEGORIA=C.COD_CATEGORIA
        JOIN SUCURSAL_HERRAMIENTA SH
        ON H.COD_HERRAMIENTA = SH.COD_HERRAMIENTA
        FULL OUTER JOIN DETALLE D 
        ON D.COD_H=H.COD_HERRAMIENTA
        WHERE H.COD_HERRAMIENTA NOT IN (SELECT H.COD_HERRAMIENTA FROM ARRIENDO A JOIN DETALLE D 
                                    ON A.COD_ARRIENDO=D.ID_A JOIN HERRAMIENTA H
                                    ON D.COD_H=H.COD_HERRAMIENTA
                                    WHERE A.FECHA_INICIO BETWEEN FECHA_I AND FECHA_F
                                    OR A.FECHA_FINAL BETWEEN FECHA_I AND FECHA_F)
        AND SH.COD_SUCURSAL = COD_S
        AND SH.COD_HERRAMIENTA = COD_HE
        AND SH.STOCK > 0);
        RETURN CANTIDADES;
    ELSE
        RETURN -1;
    END IF;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RETURN -1;
            ROLLBACK;
END;

CREATE OR REPLACE FUNCTION VACIAR_CARRO(
    RUT_U IN USUARIO.RUT%TYPE)
    RETURN BOOLEAN
IS
BEGIN
    LOCK TABLE CARRITO IN ROW EXCLUSIVE MODE;
    DELETE FROM CARRITO WHERE RUT = RUT_U;
    COMMIT;
    RETURN TRUE;
    EXCEPTION
        WHEN OTHERS THEN
            RETURN FALSE;
            ROLLBACK;
END;

CREATE OR REPLACE FUNCTION VALIDAR_LOGIN
    (USUARIO  IN  VARCHAR2,
    PASS  IN  VARCHAR2)
    RETURN BOOLEAN
AS
    PASS_DB VARCHAR2(100);
    L_SAL VARCHAR2(30) := 'CONSTRUOK-PIPEMAX-1994';
BEGIN
    SELECT PASS INTO PASS_DB FROM USUARIO WHERE RUT = USUARIO;
    IF PASS_DB = DBMS_CRYPTO.HASH(UTL_RAW.CAST_TO_RAW(L_SAL || PASS),DBMS_CRYPTO.HASH_SH1) THEN
        RETURN TRUE;
    ELSE
        RETURN FALSE;
    END IF;
    EXCEPTION 
        WHEN NO_DATA_FOUND THEN
            RETURN FALSE;
        WHEN OTHERS THEN
            RETURN FALSE;
END;