GRANT RESOURCE TO PIPEMAX;
GRANT INSERT ON USUARIO TO PIPEMAX;
GRANT CREATE SESSION TO PIPEMAX;
GRANT SELECT ON USUARIO TO PIPEMAX;
GRANT SELECT ON ARRIENDO TO PIPEMAX;
GRANT SELECT ON DETALLE TO PIPEMAX;
GRANT SELECT ON HERRAMIENTA TO PIPEMAX;
GRANT SELECT ON CATEGORIA TO PIPEMAX;
GRANT SELECT ON SUCURSAL TO PIPEMAX;
GRANT SELECT ON CARRITO TO PIPEMAX;
GRANT SELECT ON SUCURSAL_HERRAMIENTA TO PIPEMAX;


-- PRIVILEGIOS DE PROCEDIMIENTOS
--PARA USAR EL DBMS_CRYPTO EN EL SISTEMA, SE DEBE DAR PRIVILEGIOS COMO SYSDBA
--CONNECT /AS SYSDBA;
--GRANT EXECUTE ON SYS.DBMS_CRYPTO to JEFE;
-- GRANT EXECUTE ON NOMBRE TO PIPEMAX; --PARA PROCEDIMIENTOS
GRANT EXECUTE ON INSERTAR_USUARIO TO PIPEMAX;
GRANT EXECUTE ON ELIMINAR_USUARIO TO PIPEMAX;
GRANT EXECUTE ON ACTUALIZAR_USER TO PIPEMAX;
GRANT EXECUTE ON VERIFICARUT TO PIPEMAX;
GRANT EXECUTE ON OBTENERPASS TO PIPEMAX;
GRANT EXECUTE ON NUEVA_HERRAMIENTA TO PIPEMAX;
GRANT EXECUTE ON NUEVA_CATEGORIA TO PIPEMAX;
GRANT EXECUTE ON AUMENTAR_STOCK TO PIPEMAX;
GRANT EXECUTE ON QUITAR_STOCK TO PIPEMAX;
GRANT EXECUTE ON AGREGA_CARRITO TO PIPEMAX;
GRANT EXECUTE ON VACIAR_CARRITO TO PIPEMAX;
GRANT EXECUTE ON QUITA_CARRITO TO PIPEMAX;
GRANT EXECUTE ON VINCULAR_HERRAMIENTA_SUCURSAL TO PIPEMAX;
GRANT EXECUTE ON ACTUALIZAR_H_SUCURSAL TO PIPEMAX;
GRANT EXECUTE ON DESVINCULAR_H_SUCURSAL TO PIPEMAX;
GRANT EXECUTE ON NUEVA_SUCURSAL TO PIPEMAX;
GRANT EXECUTE ON INICIO_SESION TO PIPEMAX;
GRANT EXECUTE ON BORRAR_HERRAMIENTA_CARRITO TO PIPEMAX;
GRANT EXECUTE ON ARRENDAR TO PIPEMAX;

