SET SERVEROUTPUT ON;
SELECT * FROM JEFE.CATEGORIA;
SELECT RUT,NOMBRES,APELLIDOS,ROL,CORREO,ESTADO,DIRECCION,CELULAR,PASS FROM JEFE.USUARIO;
DECLARE 
    BOLEANO VARCHAR2(100);
    MENSAJE VARCHAR2(200);
BEGIN
    --JEFE.INSERTAR_USUARIO(185756203,'FELIPE MAXIMILIANO','TAPIA GOMEZ','FTAPIA46@GMAIL.COM','PIPEMAX','TALCA',986520661,BOLEANO,MENSAJE);
    --JEFE.ACTUALIZAR_USER(185756203,'PIPIN','THE REAL','XD@HOTMAIL.COM','MI CASA',111111,BOLEANO,MENSAJE);
    --JEFE.ELIMINAR_USUARIO(185756203,BOLEANO,MENSAJE);
    --JEFE.VERIFICARUT(185756203,BOLEANO,MENSAJE);
    --JEFE.NUEVA_CATEGORIA('OBRA GRUESA',BOLEANO,MENSAJE);
    --JEFE.NUEVA_HERRAMIENTA(2,'CORTADORA DE PAVIMENTO 14 HP, WACKER','Corte de asfaltos y pavimentos con disco de 14 y 16 pulgadas. PESO: 94KG','',13290,1,2,BOLEANO,MENSAJE);
    --JEFE.AUMENTAR_STOCK(2,1,1,BOLEANO,MENSAJE);
    JEFE.AGREGA_CARRITO(185756203,1,1,1,BOLEANO,MENSAJE);
    --JEFE.QUITA_CARRITO(185756203,1,1,2,BOLEANO,MENSAJE);
    --JEFE.VACIAR_CARRITO(185756203,BOLEANO,MENSAJE);
    --JEFE.QUITAR_STOCK(2,1,1,BOLEANO,MENSAJE);
    --JEFE.OBTENERPASS(185756204,BOLEANO,MENSAJE);
    --JEFE.VINCULAR_HERRAMIENTA_SUCURSAL(2,1,13290,3,BOLEANO,MENSAJE);
    --JEFE.ACTUALIZAR_H_SUCURSAL(1,1,14390,4,BOLEANO,MENSAJE);
    --JEFE.DESVINCULAR_H_SUCURSAL(1,1,BOLEANO,MENSAJE);
    DBMS_OUTPUT.PUT_LINE(BOLEANO);
    DBMS_OUTPUT.PUT_LINE(MENSAJE);
END;  

SELECT A.COD_ARRIENDO,A.FECHA_INICIO,A.FECHA_FINAL,A.TOTAL,A.RUT_U,U.NOMBRES,U.APELLIDOS,A.FECHA_ARRIENDO,S.COD_SUCURSAL,S.NOMBRE
FROM JEFE.ARRIENDO A JOIN JEFE.SUCURSAL S 
ON A.COD_S = S.COD_SUCURSAL JOIN JEFE.USUARIO U
ON A.RUT_U = U.RUT
WHERE COD_ARRIENDO = 61
AND U.RUT = 185756203;
SELECT D.COD_H, H.NOMBRE,H.URL_FOTO,D.CANTIDAD,D.TOTAL_DETALLE,SH.PRECIO FROM JEFE.DETALLE D JOIN JEFE.HERRAMIENTA H
ON D.COD_H = H.COD_HERRAMIENTA JOIN JEFE.SUCURSAL_HERRAMIENTA SH
ON H.COD_HERRAMIENTA = SH.COD_HERRAMIENTA
WHERE ID_A = 61
AND SH.COD_SUCURSAL = 1;

set serveroutput on;

DECLARE 
    BOLEANO VARCHAR2(100);
    MENSAJE VARCHAR2(200);
BEGIN
    JEFE.NUEVA_HERRAMIENTA(1791699,'ASPIRADORA SEMI-INDUSTRIAL A MOTOR 1000 W, LUSTER','Para aspirado de polvo y agua y residuos ligeros','aspiradora2.jpg',33,BOLEANO,MENSAJE);
    JEFE.VINCULAR_HERRAMIENTA_SUCURSAL(1791699,1,5590,11,BOLEANO,MENSAJE);
    --JEFE.VINCULAR_HERRAMIENTA_SUCURSAL(1791680,2,8090,7,BOLEANO,MENSAJE);
    --JEFE.NUEVA_CATEGORIA('ASEO',BOLEANO,MENSAJE);
    DBMS_OUTPUT.PUT_LINE(BOLEANO);
    DBMS_OUTPUT.PUT_LINE(MENSAJE);
END;  

SELECT * FROM JEFE.HERRAMIENTA;
SELECT * FROM JEFE.USUARIO;
SELECT * FROM JEFE.CARRITO;
SELECT * FROM JEFE.ARRIENDO ORDER BY COD_ARRIENDO DESC WHERE COD_ARRIENDO = 61;
SELECT * FROM JEFE.SUCURSAL;
SELECT * FROM JEFE.DETALLE;
SELECT * FROM JEFE.CATEGORIA;
SELECT * FROM JEFE.SUCURSAL_HERRAMIENTA;
SELECT H.URL_FOTO,SH.STOCK FROM JEFE.HERRAMIENTA H JOIN JEFE.SUCURSAL_HERRAMIENTA SH
ON H.COD_HERRAMIENTA = SH.COD_HERRAMIENTA
WHERE SH.COD_SUCURSAL = 1;
SELECT * FROM JEFE.ARRIENDO JOIN JEFE.DETALLE 
ON JEFE.ARRIENDO.COD_ARRIENDO = JEFE.DETALLE.ID_A
WHERE JEFE.ARRIENDO.COD_ARRIENDO = 61
ORDER BY COD_ARRIENDO DESC;

SELECT H.COD_HERRAMIENTA,H.NOMBRE,H.DESCRIPCION,H.URL_FOTO,H.COD_CATEGORIA,S.COD_SUCURSAL,SH.PRECIO,SH.STOCK
FROM JEFE.HERRAMIENTA H JOIN JEFE.SUCURSAL_HERRAMIENTA SH
ON H.COD_HERRAMIENTA = SH.COD_HERRAMIENTA
JOIN JEFE.SUCURSAL S
ON SH.COD_SUCURSAL = S.COD_SUCURSAL
JOIN JEFE.CATEGORIA C
ON H.COD_CATEGORIA = C.COD_CATEGORIA
WHERE S.COD_SUCURSAL = 2;

SELECT C.COD_CATEGORIA,C.NOMBRE FROM JEFE.CATEGORIA C
JOIN JEFE.HERRAMIENTA H
ON H.COD_CATEGORIA = C.COD_CATEGORIA
JOIN JEFE.SUCURSAL_HERRAMIENTA SH
ON SH.COD_HERRAMIENTA = H.COD_HERRAMIENTA
WHERE SH.COD_SUCURSAL = 2
GROUP BY C.COD_CATEGORIA,C.NOMBRE;

SELECT C.COD_CATEGORIA,C.NOMBRE, COUNT(H.COD_HERRAMIENTA) AS CONTADOR FROM JEFE.CATEGORIA C
JOIN JEFE.HERRAMIENTA H
ON H.COD_CATEGORIA = C.COD_CATEGORIA
JOIN JEFE.SUCURSAL_HERRAMIENTA SH
ON SH.COD_HERRAMIENTA = H.COD_HERRAMIENTA
WHERE SH.COD_SUCURSAL = 2
GROUP BY C.COD_CATEGORIA,C.NOMBRE;

SELECT C.COD_HERRAMIENTA, H.NOMBRE, H.URL_FOTO, C.CANTIDAD, SH.STOCK, C.TOTAL, SH.PRECIO FROM JEFE.CARRITO C
JOIN JEFE.HERRAMIENTA H
ON C.COD_HERRAMIENTA = H.COD_HERRAMIENTA
JOIN JEFE.SUCURSAL_HERRAMIENTA SH
ON SH.COD_HERRAMIENTA = H.COD_HERRAMIENTA
WHERE SH.COD_SUCURSAL = 2
AND C.RUT = 185756203;


--HERAMIENTAS AGREGADAS
--JEFE.NUEVA_HERRAMIENTA(1,'ALISADOR DE HORMIG�N 36 PULGADAS 9.0 HP','PARA ALISADO DE SUPERFICIES DE HORMIG�N FRESCO, HASTA 2 HORAS DE APLICADO. PESO: 85KG.','',1,BOLEANO,MENSAJE);
--JEFE.VINCULAR_HERRAMIENTA_SUCURSAL(1,1,14390,4,BOLEANO,MENSAJE);
--JEFE.NUEVA_HERRAMIENTA(2,'CORTADORA DE PAVIMENTO 14 HP, WACKER','Corte de asfaltos y pavimentos con disco de 14 y 16 pulgadas. PESO: 94KG','',1,BOLEANO,MENSAJE);
--JEFE.VINCULAR_HERRAMIENTA_SUCURSAL(2,1,13290,3,BOLEANO,MENSAJE);