/*SELECT PARA MOSTRAR TODOS LOS PRODUCTOS EN FUNCION AL INTERVALO FECHA*/
(SELECT H.COD_HERRAMIENTA, H.NOMBRE, H.DESCRIPCION, H.URL_FOTO, SH.PRECIO, C.NOMBRE AS NOMBREC, (SH.STOCK - SUM(D.CANTIDAD)) AS STOCK
FROM HERRAMIENTA H JOIN CATEGORIA C 
ON H.COD_CATEGORIA=C.COD_CATEGORIA
JOIN SUCURSAL_HERRAMIENTA SH
ON H.COD_HERRAMIENTA = SH.COD_HERRAMIENTA
JOIN DETALLE D 
ON D.COD_H=H.COD_HERRAMIENTA
WHERE H.COD_HERRAMIENTA IN (SELECT H.COD_HERRAMIENTA FROM ARRIENDO A JOIN DETALLE D 
                            ON A.COD_ARRIENDO=D.ID_A JOIN HERRAMIENTA H
                            ON D.COD_H=H.COD_HERRAMIENTA
                            WHERE A.FECHA_INICIO BETWEEN '08/07/2018' AND '10/08/2018'
                            OR A.FECHA_FINAL BETWEEN '08/07/2018' AND '10/08/2018')
AND SH.COD_SUCURSAL = 1
GROUP BY H.COD_HERRAMIENTA, H.NOMBRE, H.DESCRIPCION, H.URL_FOTO, SH.PRECIO, C.NOMBRE, SH.STOCK
HAVING (SH.STOCK - SUM(D.CANTIDAD)) > 0
UNION
SELECT H.COD_HERRAMIENTA AS CODIGO,H.NOMBRE,H.DESCRIPCION, H.URL_FOTO, SH.PRECIO, C.NOMBRE AS NOMBREC, SH.STOCK AS STOCK
FROM HERRAMIENTA H JOIN CATEGORIA C 
ON H.COD_CATEGORIA=C.COD_CATEGORIA
JOIN SUCURSAL_HERRAMIENTA SH
ON H.COD_HERRAMIENTA = SH.COD_HERRAMIENTA
FULL OUTER JOIN DETALLE D 
ON D.COD_H=H.COD_HERRAMIENTA
WHERE H.COD_HERRAMIENTA NOT IN (SELECT H.COD_HERRAMIENTA FROM ARRIENDO A JOIN DETALLE D 
                            ON A.COD_ARRIENDO=D.ID_A JOIN HERRAMIENTA H
                            ON D.COD_H=H.COD_HERRAMIENTA
                            WHERE A.FECHA_INICIO BETWEEN '08/07/2018' AND '10/08/2018'
                            OR A.FECHA_FINAL BETWEEN '08/07/2018' AND '10/08/2018')
AND SH.COD_SUCURSAL = 1
AND SH.STOCK > 0);
SELECT COD_HERRAMIENTA,NOMBRE FROM HERRAMIENTA;

SELECT * FROM ARRIENDO;
SELECT * FROM DETALLE;
INSERT INTO ARRIENDO VALUES(ARRIENDO_AI.NEXTVAL,'08/07/2018','10/07/2018',14390,185756203,1,'ACTIVO');
INSERT INTO DETALLE VALUES(1,1,14390,1);
COMMIT;
select * from herramienta;
select * from categoria;

--SELECT QUE MUESTRA HERRAMIENTAS DE CIERTA SUCURSAL
SELECT H.COD_HERRAMIENTA,H.NOMBRE,H.DESCRIPCION,H.URL_FOTO,H.COD_CATEGORIA,S.COD_SUCURSAL,SH.PRECIO,SH.STOCK
FROM HERRAMIENTA H JOIN SUCURSAL_HERRAMIENTA SH
ON H.COD_HERRAMIENTA = SH.COD_HERRAMIENTA
JOIN SUCURSAL S
ON SH.COD_SUCURSAL = S.COD_SUCURSAL
JOIN CATEGORIA C
ON H.COD_CATEGORIA = C.COD_CATEGORIA
WHERE S.COD_SUCURSAL = 2;

SELECT H.COD_HERRAMIENTA AS CODIGO,H.NOMBRE,H.DESCRIPCION, H.URL_FOTO, H.PRECIO, C.NOMBRE AS NOMBREC, H.STO
FROM HERRAMIENTA H JOIN CATEGORIA C CK
ON H.COD_CATEGORIA=C.COD_CATEGORIA
WHERE H.STOCK>0 AND C.COD_CATEGORIA = 1; 

SELECT D.COD_H, H.NOMBRE, H.URL_FOTO,SH.PRECIO, COUNT(D.ID_A) AS CANTIDAD_ARRIENDOS 
FROM DETALLE D JOIN HERRAMIENTA H
ON D.COD_H = H.COD_HERRAMIENTA
JOIN SUCURSAL_HERRAMIENTA SH
ON SH.COD_HERRAMIENTA = H.COD_HERRAMIENTA
WHERE SH.COD_SUCURSAL = 2
GROUP BY COD_H, H.NOMBRE, H.URL_FOTO, SH.PRECIO ORDER BY CANTIDAD_ARRIENDOS DESC;


SELECT (SH.STOCK - SUM(D.CANTIDAD)) AS STOCK
FROM HERRAMIENTA H JOIN CATEGORIA C 
ON H.COD_CATEGORIA=C.COD_CATEGORIA
JOIN SUCURSAL_HERRAMIENTA SH
ON H.COD_HERRAMIENTA = SH.COD_HERRAMIENTA
JOIN DETALLE D 
ON D.COD_H=H.COD_HERRAMIENTA
WHERE H.COD_HERRAMIENTA = 932965
AND SH.COD_SUCURSAL = 2
GROUP BY H.COD_HERRAMIENTA, H.NOMBRE, H.DESCRIPCION, H.URL_FOTO, SH.PRECIO, C.NOMBRE, SH.STOCK


