CREATE OR REPLACE TRIGGER CATEGORIA_AI
    BEFORE INSERT ON CATEGORIA
    FOR EACH ROW
BEGIN
    :NEW.COD_CATEGORIA:=CATEGORIA_AI.NEXTVAL;
END;   

CREATE OR REPLACE TRIGGER MAYUS_HERRAMIENTA
    BEFORE INSERT ON HERRAMIENTA
    FOR EACH ROW
BEGIN
    :NEW.NOMBRE := UPPER(:NEW.NOMBRE);
    :NEW.DESCRIPCION := UPPER(:NEW.DESCRIPCION);
END;

CREATE OR REPLACE TRIGGER MAYUS_USUARIO
    BEFORE INSERT ON USUARIO
    FOR EACH ROW
BEGIN
    :NEW.NOMBRES := UPPER(:NEW.NOMBRES);
    :NEW.APELLIDOS := UPPER(:NEW.APELLIDOS);
    :NEW.CORREO := UPPER(:NEW.CORREO);
    :NEW.DIRECCION := UPPER(:NEW.DIRECCION);
END;

CREATE OR REPLACE TRIGGER MAYUS_SUCURSAL
    BEFORE INSERT ON SUCURSAL
    FOR EACH ROW
BEGIN
    :NEW.NOMBRE := UPPER(:NEW.NOMBRE);
END;

CREATE OR REPLACE TRIGGER AJUSTA_TOTAL_CARRITO_INSERT
    BEFORE INSERT ON CARRITO
    FOR EACH ROW
DECLARE
    TOTAL_PRODUCTO NUMBER;
BEGIN
    SELECT PRECIO INTO TOTAL_PRODUCTO FROM SUCURSAL_HERRAMIENTA 
    WHERE COD_HERRAMIENTA = :NEW.COD_HERRAMIENTA
    AND COD_SUCURSAL = :NEW.COD_SUCURSAL;
    :NEW.TOTAL := (TOTAL_PRODUCTO*:NEW.CANTIDAD);
END;


CREATE OR REPLACE TRIGGER AJUSTA_TOTAL_CARRITO_UPDATE
    BEFORE UPDATE ON CARRITO
    FOR EACH ROW
DECLARE 
    TOTAL_PRODUCTO NUMBER;
BEGIN
    SELECT PRECIO INTO TOTAL_PRODUCTO FROM SUCURSAL_HERRAMIENTA 
    WHERE COD_HERRAMIENTA = :NEW.COD_HERRAMIENTA
    AND COD_SUCURSAL = :NEW.COD_SUCURSAL;
    :NEW.TOTAL := :NEW.CANTIDAD*TOTAL_PRODUCTO;
END;

CREATE OR REPLACE TRIGGER ACTUALIZA_TOTAL_ARRIENDO
    AFTER INSERT ON DETALLE
    FOR EACH ROW
DECLARE
    SUCURSAL NUMBER;
BEGIN
    SELECT COD_S INTO SUCURSAL FROM ARRIENDO WHERE COD_ARRIENDO = :NEW.ID_A;
    UPDATE ARRIENDO
    SET TOTAL = TOTAL + :NEW.TOTAL_DETALLE
    WHERE COD_ARRIENDO = :NEW.ID_A;
END;

